server:
  port: 8082

spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/messageservice
      username: postgres
      password: Babu@895805
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
    application:
      name: CS-SERVICE
